import { 
  Home, Users, Dog, Calendar, Activity, Bell, Settings, 
  BarChart, Image, Video, Shield, Award, FileText, LayoutTemplate, 
  CreditCard, LifeBuoy, Download, Tent, Trophy, PenTool, Layout, Lock, MessageSquare
} from 'lucide-react';

export const ADMIN_ROUTES = [
  { name: 'Dashboard', icon: Home, roles: ['SUPER_ADMIN', 'ADMIN'], children: [
    { name: 'Dashboard', href: '/admin' },
    { name: 'Analytics', href: '/admin/analytics' },
    { name: 'Activity', href: '/admin/activity' },
  ]},
  { name: 'Users', icon: Users, roles: ['SUPER_ADMIN', 'ADMIN'], children: [
    { name: 'All Users', href: '/admin/users' },
    { name: 'Add User', href: '/admin/users/create' },
    { name: 'Roles', href: '/admin/users/roles' },
    { name: 'Permissions', href: '/admin/users/permissions' },
  ]},
  { name: 'Judges', icon: Award, roles: ['SUPER_ADMIN', 'ADMIN'], children: [
    { name: 'All Judges', href: '/admin/judges' },
    { name: 'Add Judge', href: '/admin/judges/create' },
    { name: 'Bulk Upload Judges', href: '/admin/bulk-upload?module=judges' },
    { name: 'Judge Categories', href: '/admin/judges/categories' },
    { name: 'Judge Requests', href: '/admin/judges/requests' },
  ]},
  { name: 'KCI Clubs', icon: Tent, roles: ['SUPER_ADMIN', 'ADMIN'], children: [
    { name: 'KCI Clubs', href: '/admin/clubs' },
    { name: 'Add Club', href: '/admin/clubs/create' },
    { name: 'Bulk Upload Clubs', href: '/admin/bulk-upload?module=clubs' },
  ]},
  { name: 'Dog Shows', icon: Trophy, roles: ['SUPER_ADMIN', 'ADMIN'], children: [
    { name: 'All Shows', href: '/admin/events' },
    { name: 'Create Show', href: '/admin/events/create' },
    { name: 'Show Catalogs', href: '/admin/events' },
    { name: 'Bulk Upload Shows', href: '/admin/bulk-upload?module=events' },
    { name: 'Calendar', href: '/admin/events/calendar' },
    { name: 'Upcoming', href: '/admin/events/upcoming' },
    { name: 'Completed', href: '/admin/events/completed' },
    { name: 'Results', href: '/admin/competition/results' },
  ]},
  { name: 'Entries', icon: FileText, roles: ['SUPER_ADMIN', 'ADMIN'], children: [
    { name: 'All Entries', href: '/admin/entries' },
    { name: 'Pending Entries', href: '/admin/entries/pending' },
    { name: 'Approved Entries', href: '/admin/entries/approved' },
    { name: 'Rejected Entries', href: '/admin/entries/rejected' },
    { name: 'Add Entry', href: '/admin/entries/create' },
    { name: 'Bulk Upload Entries', href: '/admin/bulk-upload?module=entries' },
    { name: 'Entry Categories', href: '/admin/entries/categories' },
    { name: 'Entry Requests', href: '/admin/entries/requests' },
  ]},
  { name: 'Winner Management', icon: Award, roles: ['SUPER_ADMIN', 'ADMIN'], children: [
    { name: 'Winners List', href: '/admin/winners' },
    { name: 'Add Winner', href: '/admin/winners/create' },
    { name: 'Winner Categories', href: '/admin/winners/categories' },
    { name: 'Hall Of Fame', href: '/admin/winners/hall-of-fame' },
    { name: 'Special Awards', href: '/admin/winners/special-awards' },
  ]},
  { name: 'Media Management', icon: Image, roles: ['SUPER_ADMIN', 'ADMIN'], children: [
    { name: 'Media Gallery Mgmt', href: '/admin/media-gallery-mgmt' },
    { name: 'All Photos', href: '/admin/media/photos' },
    { name: 'Upload Photo', href: '/admin/media/photos/create' },
    { name: 'Photo Categories', href: '/admin/media/photos/categories' },
    { name: 'Albums', href: '/admin/media/photos/albums' },
    { name: 'Featured Photos', href: '/admin/media/photos/featured' },
    { name: 'All Videos', href: '/admin/media/videos' },
    { name: 'Upload Video', href: '/admin/media/videos/create' },
    { name: 'Video Categories', href: '/admin/media/videos/categories' },
    { name: 'Featured Videos', href: '/admin/media/videos/featured' },
  ]},
  { name: 'Content Management', icon: LayoutTemplate, roles: ['SUPER_ADMIN', 'ADMIN'], children: [
    { name: 'E-Magazines', href: '/admin/e-magazines' }
  ]},
  { name: 'CMS', icon: LayoutTemplate, roles: ['SUPER_ADMIN', 'ADMIN'], children: [
    { name: 'Homepage Banner', href: '/admin/cms/homepage-banners' },
    { name: 'Page Banners', href: '/admin/cms/page-banners' },
    { name: 'Homepage Show Photos', href: '/admin/cms/show-photos' },
    { name: 'Homepage Outdoor Photos', href: '/admin/cms/outdoor-photos' },
    { name: 'Sliding Photo Sections', href: '/admin/cms/sliding-sections' },
    { name: 'About Home Section', href: '/admin/cms/about' },
    { name: 'Featured Sections', href: '/admin/cms/featured' },
    { name: 'SEO', href: '/admin/cms/seo' },
    { name: 'Footer', href: '/admin/cms/footer' },
    { name: 'Testimonials', href: '/admin/cms/testimonials' },
    { name: 'FAQ', href: '/admin/cms/faqs' },
  ]},
  { name: 'Settings', icon: Settings, roles: ['SUPER_ADMIN', 'ADMIN'], children: [
    { name: 'General', href: '/admin/settings/general' },
    { name: 'Email', href: '/admin/settings/email' },
    { name: 'AWS S3', href: '/admin/settings/aws' },
    { name: 'Logo', href: '/admin/settings/logo' },
    { name: 'SEO', href: '/admin/settings/seo' },
    { name: 'Social Links', href: '/admin/settings/social' },
    { name: 'Theme', href: '/admin/settings/theme' },
    { name: 'Payment Gateway', href: '/admin/settings/payment-gateway' },
  ]},
  { name: 'Notifications', icon: Bell, roles: ['SUPER_ADMIN', 'ADMIN'], children: [
    { name: 'Push Notifications', href: '/admin/notifications/push' },
    { name: 'Email Templates', href: '/admin/notifications/email' },
    { name: 'SMS Templates', href: '/admin/notifications/sms' },
  ]},
  { name: 'Reports', icon: BarChart, roles: ['SUPER_ADMIN', 'ADMIN'], children: [
    { name: 'Revenue', href: '/admin/reports/revenue' },
    { name: 'Users', href: '/admin/reports/users' },
    { name: 'Shows', href: '/admin/reports/shows' },
    { name: 'Entries', href: '/admin/reports/entries' },
    { name: 'Media', href: '/admin/reports/media' },
    { name: 'Downloads', href: '/admin/reports/downloads' },
  ]},
  { name: 'Payments', icon: CreditCard, roles: ['SUPER_ADMIN', 'ADMIN'], children: [
    { name: 'Transactions', href: '/admin/payments/transactions' },
    { name: 'Refunds', href: '/admin/payments/refunds' },
    { name: 'Payouts', href: '/admin/payments/payouts' },
    { name: 'Invoices', href: '/admin/payments/invoices' },
  ]},
  { name: 'Audit Logs', href: '/admin/audit-logs', icon: Shield, roles: ['SUPER_ADMIN', 'ADMIN'] },
];

export const USER_ROUTES = [
  { name: 'Dashboard', href: '/dashboard', icon: Home, roles: ['USER', 'BREEDER', 'OWNER'] },
  { name: 'My Profile', href: '/dashboard/profile', icon: Users, roles: ['USER', 'BREEDER', 'OWNER'] },
  { name: 'My Dogs', icon: Dog, roles: ['USER', 'BREEDER', 'OWNER'], children: [
    { name: 'All Dogs', href: '/dashboard/dogs' },
    { name: 'Add Dog', href: '/dashboard/dogs/add' },
    { name: 'Upload KCI', href: '/dashboard/dogs/kci' },
    { name: 'Certificates', href: '/dashboard/dogs/certificates' },
  ]},
  { name: 'My Events', icon: Calendar, roles: ['USER', 'BREEDER', 'OWNER'], children: [
    { name: 'Upcoming Events', href: '/dashboard/events/upcoming' },
    { name: 'Registered Events', href: '/dashboard/events/registered' },
    { name: 'Past Events', href: '/dashboard/events/past' },
  ]},
  { name: 'Payments', icon: CreditCard, roles: ['USER', 'BREEDER', 'OWNER'], children: [
    { name: 'Invoices', href: '/dashboard/payments/invoices' },
    { name: 'Refunds', href: '/dashboard/payments/refunds' },
  ]},
  { name: 'Winner Tags', href: '/dashboard/winners', icon: Award, roles: ['USER', 'BREEDER', 'OWNER'] },
  { name: 'Notifications', href: '/dashboard/notifications', icon: Bell, roles: ['USER', 'BREEDER', 'OWNER'] },
  { name: 'Downloads', href: '/dashboard/downloads', icon: Download, roles: ['USER', 'BREEDER', 'OWNER'] },
  { name: 'Support', href: '/dashboard/support', icon: LifeBuoy, roles: ['USER', 'BREEDER', 'OWNER'] },
  { name: 'Settings', href: '/dashboard/settings', icon: Settings, roles: ['USER', 'BREEDER', 'OWNER'] },
];
